### ISSUE TITLE
Using Navigator.delete

### ISSUE THREAD

**Issue by ryanjnorris** [dherges/ng-hal#27]
When using `navigator.delete()` the server implementation i'm using just returns a 204 and an empty response.  NgHal is trying to convert the response, and the result is

`
TypeError: Cannot read property '_links' of null
    at new InternalResourceWrapper (http://localhost:8100/build/main.js:113747:46)
    at Parser.parse (http://localhost:8100/build/main.js:113787:16)
    at JsonConversionStrategy.convert (http://localhost:8100/build/main.js:113660:28)
    at Navigator.doConvert (http://localhost:8100/build/main.js:76800:48)
    at MapSubscriber.project (http://localhost:8100/build/main.js:76797:53)
    at MapSubscriber._next (http://localhost:8100/build/main.js:77054:35)
    at MapSubscriber.Subscriber.next (http://localhost:8100/build/main.js:35433:18)
    at XMLHttpRequest.onLoad (http://localhost:8100/build/main.js:57364:38)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655)
    at Object.onInvokeTask (http://localhost:8100/build/main.js:4397:37)`

My code

`
        this.navigator.delete(shopResource.link("self").href)
            .subscribe(() => this.getShops());
`

Is the server implementation (Spring HATEOAS) wrong to return nothing?  Or is NgHal trying to parse content that doesn't exist?

**Comment by dherges** [comment]
Hi  @ryanjnorris,

please excuse my response time.

The [`JsonConversionStrategy`](../blob/develop/src/lib/src/conversion/json-conversion-strategy.ts#L15-L19) reads the response body in JSON format when it finds a `Content-Type` header for JSON.

Can you provide the request/response pair (e.g. with `curl -v`) that causes the error?

**Comment by ekoch** [comment]
I have the same issue. With a 204 returned by the server, there is no body at all, thus nothing to read for the JsonConversionStrategy.

 curl -v -X DELETE http://localhost:8080/1/admin/message/24
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> DELETE /1/admin/message/24 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 204 
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< Date: Tue, 25 Jul 2017 14:21:43 GMT
< 
* Connection #0 to host localhost left intact

**Comment by ekoch** [comment]
Fixed by patching line json-conversion-strategy.js:12 with
        return data == null ? null : this.parser.parse(data);
